name: Build and Publish Wheels

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up QEMU for Linux ARM builds
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.21.3

      - name: Build wheels
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "pp* *-musllinux_*"
          # Use manylinux_2_28 (AlmaLinux 8) to avoid CentOS 7 EOL issues
          # These images have working repositories and include gcc by default
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux_2_28_x86_64
          CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux_2_28_aarch64
          # Install dependencies - gcc is already available in manylinux_2_28 images
          CIBW_BEFORE_BUILD: "python -m pip install --upgrade setuptools wheel Cython numpy"
          CIBW_BEFORE_BUILD_LINUX: "python -m pip install --upgrade setuptools wheel Cython numpy"
          # On Windows, install without upgrade flag to avoid pip modification issues
          CIBW_BEFORE_BUILD_WINDOWS: "python -m pip install setuptools wheel Cython numpy"
          CIBW_TEST_COMMAND: "python -c \"import fa2_modified; print('Import successful')\""
          CIBW_TEST_REQUIRES: "numpy scipy tqdm"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_BUILD_VERBOSITY: 1
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build sdist (source)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install build Cython
          python -m build --sdist --outdir wheelhouse

      - name: List built wheels
        shell: bash
        run: ls -lh wheelhouse/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: wheelhouse/*
          if-no-files-found: error

  publish:
    name: Publish to PyPI
    needs: build-wheels
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fa2-modified
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: List all files to publish
        shell: bash
        run: ls -lh dist/

      - name: Verify wheels
        run: |
          pip install twine
          twine check dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN_GITHUB }}
          packages-dir: dist
          verbose: true
          print-hash: true
